apiVersion: v1
data: 
  nginx.conf: |
    worker_processes auto;

    events {
        worker_connections 1024;
    }

    http {
        access_log off;
        error_log stderr;

        proxy_read_timeout 300;
        proxy_send_timeout 300;

        upstream registry {
            server localhost:5003;
        }

        server {
            listen 5000;

            proxy_buffering off;

            client_max_body_size 2G; # No image should be bigger than this.

            location = / {
                return 200 'HEALTHY';
            }

            location / {
                proxy_pass http://registry;
                proxy_set_header Host $host;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto "https";
            }
        }
    }
kind: ConfigMap
metadata: 
  name: nexus-nginx-conf
